### ISSUE TITLE
temp文件丢失 240512

### ISSUE THREAD

**Issue by Zhangzy-54** [Caritusy/RE-JavaTexturePackage2NeteaseBedrockTexturePackage#2]
240512
windows11运行环境，程序无法找到temp文件夹下的缓存文件

这应该是由于系统清理缓存，导致旧的缓存文件丢失

增加文件存在验证应该可以解决

************** 异常文本 **************
System.IO.FileNotFoundException: Could not find file 'C:\Users\35095\AppData\Local\Temp\REJTP2BTP-fe6d980133cee19f676e7a577010242d\pack.mcmeta'.
File name: 'C:\Users\35095\AppData\Local\Temp\REJTP2BTP-fe6d980133cee19f676e7a577010242d\pack.mcmeta'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at RE_JavaTexturePackage2NBTP.JavaPackage..ctor(String path)
   at RE_JavaTexturePackage2NBTP.Form1.button2_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
System.Private.CoreLib
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Private.CoreLib.dll
----------------------------------------
RE_JavaTexturePackage2NBTP
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    程序集版本:6.0.2.0
    Win32 版本:6.0.2123.36406
    代码库:file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.21/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    程序集版本:6.0.2.0
    Win32 版本:6.0.2123.36406
    代码库:file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.21/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Collections.Specialized.dll
----------------------------------------
System.Threading
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Collections.dll
----------------------------------------
System.Drawing.Common
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.21/System.Drawing.Common.dll
----------------------------------------
Microsoft.Win32.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.21/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/6.0.21/System.Threading.Thread.dll
----------------------------------------
Accessibility

**Comment by xiaojiang233** [comment]
你这有点太巧了吧，怎么正好就在文件夹刚创建JavaPackage构造方法还没运行完文件夹就被删了
